name: Comment Rebase
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge emoji
        uses: actions-cool/emoji-helper@v1.0.0
        with:
          type: "comment"
          emoji: "+1"
          token: ${{secrets.TEST_SECRET}}
          comment-id: ${{github.event.comment.id}}
      - name: Temporarily Update PR Title
        uses: actions-cool/issues-helper@v2
        with:
          actions: "update-issue"
          token: ${{ secrets.TEST_SECRET }}
          issue-number: ${{ github.event.issue.number }}
          title: ${{format('{0} ♺ Rebasing ♺', github.event.issue.title)}}
          update-mode: "replace"
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TEST_SECRET }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_SECRET }}
      - name: Update Title Back
        if: always()
        uses: actions-cool/issues-helper@v2
        with:
          actions: "update-issue"
          token: ${{ secrets.TEST_SECRET }}
          issue-number: ${{ github.event.issue.number }}
          title: ${{github.event.issue.title}}
          update-mode: "replace"
      - name: Success emoji
        uses: actions-cool/emoji-helper@v1.0.0
        with:
          type: "comment"
          emoji: "hooray"
          token: ${{secrets.TEST_SECRET}}
          comment-id: ${{github.event.comment.id}}
      - name: Failure emoji
        uses: actions-cool/emoji-helper@v1.0.0
        with:
          type: "comment"
          emoji: "confused"
          token: ${{secrets.TEST_SECRET}}
          comment-id: ${{github.event.comment.id}}
      - name: Update PR Title in case of fail
        # if: failure()
        uses: actions-cool/issues-helper@v2
        with:
          actions: "update-issue"
          token: ${{ secrets.TEST_SECRET }}
          issue-number: ${{ github.event.issue.number }}
          title: ${{format('{0} ❗️ Rebase Failed ❗️', github.event.issue.title)}}
          update-mode: "replace"
      - name: Failure comment
        # if: failure()
        uses: actions-cool/issues-helper@v2
        with:
          actions: "create-comment"
          token: ${{ secrets.TEST_SECRET }}
          issue-number: ${{ github.event.number }}
          body: |
            Rebase actin failed for some reason 🤔
            Check actions or ask for help from DevOps.
