name: Comment Rebase
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge emoji
        uses: actions-cool/emoji-helper@v1.0.0
        with:
          type: "comment"
          emoji: "+1"
          token: ${{secrets.TEST_SECRET}}
          comment-id: ${{github.event.comment.id}}
      - name: Temporarily Update PR Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: rebase-in-progress
          number: ${{ github.event.issue.number }}
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TEST_SECRET }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_SECRET }}
      - name: Success emoji
        uses: actions-cool/emoji-helper@v1.0.0
        with:
          type: "comment"
          emoji: "hooray"
          token: ${{secrets.TEST_SECRET}}
          comment-id: ${{github.event.comment.id}}
      - name: Failure emoji
        if: failure()
        uses: actions-cool/emoji-helper@v1.0.0
        with:
          type: "comment"
          emoji: "confused"
          token: ${{secrets.TEST_SECRET}}
          comment-id: ${{github.event.comment.id}}
      - name: Update PR Label in case of fail
        if: failure()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: rebase-failed
          number: ${{ github.event.issue.number }}
      - name: Failure comment
        if: failure()
        uses: actions-cool/issues-helper@v2
        with:
          actions: "create-comment"
          token: ${{ secrets.TEST_SECRET }}
          issue-number: ${{ github.event.number }}
          body: |
            Rebase action failed for some reason 🤔
            Check [Actions](https://github.com/Planable/planable-app/actions) or ask for help from DevOps.
