name: Label Rebase

on:
  pull_request:
    types: [labeled]

jobs:
  main:
    if: ${{ github.event.label.name == 'rebase' }}
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TEST_SECRET }}
          fetch-depth: 0
      - name: echo before rebase
        run: echo '${{github.event.title}}'
      - name: Update issue
        uses: actions-cool/issues-helper@v2
        with:
          actions: "update-issue"
          token: ${{ secrets.TEST_SECRET }}
          issue-number: ${{ github.event.number }}
          title: ${{format('Rebasing {0}', github.event.title)}}
          update-mode: "replace"
      - name: automatic rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_SECRET }}
      - name: remove label
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: rebase
      - name: echo after rebase
        run: echo '${{github.event.title}}'
      - name: Update issue
        uses: actions-cool/issues-helper@v2
        with:
          actions: "update-issue"
          token: ${{ secrets.TEST_SECRET }}
          issue-number: ${{ github.event.number }}
          title: ${{github.event.title}}
          update-mode: "replace"
