name: Label Rebase

on:
  pull_request:
    types: [labeled]

jobs:
  main:
    if: ${{ github.event.label.name == 'rebase' }}
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TEST_SECRET }}
          fetch-depth: 0
      - name: Temporarily Update PR Title
        uses: actions-cool/issues-helper@v2
        with:
          actions: "update-issue"
          token: ${{ secrets.TEST_SECRET }}
          issue-number: ${{ github.event.number }}
          title: ${{format('{0} ♺ Rebasing ♺', github.event.pull_request.title)}}
          update-mode: "replace"
      - name: automatic rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_SECRET }}
      - name: remove label
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: rebase
      - name: Update Title Back
        uses: actions-cool/issues-helper@v2
        with:
          actions: "update-issue"
          token: ${{ secrets.TEST_SECRET }}
          issue-number: ${{ github.event.number }}
          title: ${{github.event.pull_request.title}}
          update-mode: "replace"
      - name: Update PR Title in case of fail
        # if: failure()
        uses: actions-cool/issues-helper@v2
        with:
          actions: "update-issue"
          token: ${{ secrets.TEST_SECRET }}
          issue-number: ${{ github.event.number }}
          title: ${{format('{0} ❗️ Rebase Failed ❗️', github.event.pull_request.title)}}
          update-mode: "replace"
      - name: Failure comment
        # if: failure()
        uses: actions-cool/issues-helper@v2
        with:
          actions: "create-comment"
          token: ${{ secrets.TEST_SECRET }}
          issue-number: ${{ github.event.number }}
          body: |
            Rebase actin failed for some reason 🤔
            Check [Actions](https://github.com/Planable/planable-app/actions) or ask for help from DevOps.
